Jacob/html
oOoOoOo0o/CS4207-Group-Project pull request #2
Opened 2024-11-26 14:15 UTC by ShaveYourEyebrows

Add my HTML in pls

2024-11-26 14:16 UTC, oOoOoOo0o requested changes

2024-11-26 14:16 UTC, oOoOoOo0o commented on OBlock/html/frontend.html
> +		<link rel="icon" href = "shrek.png" type= "image/png"/>
Let's not use Shrek

2024-11-26 14:16 UTC, oOoOoOo0o commented on OBlock/html/shrek.png
No Shrek

2024-11-26 14:26 UTC, Bourkupine requested changes
Looks good, just minor nit picks

2024-11-26 14:26 UTC, Bourkupine commented on OBlock/html/frontend.html
> +<html lang = 'en'>
lets remove the spacing around the '=' symbol for consistency

2024-11-26 14:26 UTC, Bourkupine commented on OBlock/html/frontend.html
> +		<br></br>
dont think </br> is needed

2024-11-26 14:26 UTC, Bourkupine commented on OBlock/html/shrek.png
yeah lets not use shrek

2024-11-26 14:26 UTC, Bourkupine commented on OBlock/html/init.txt
remove this now

2024-11-26 14:26 UTC, Bourkupine commented on OBlock/html/frontend.html
> +		<br></br>
forgot comments were md, meant the /br tag

2024-11-27 22:59 UTC, carthy27 requested changes
no shrek grrrr

2024-12-01 17:35 UTC, oOoOoOo0o approved these changes

2024-12-03 15:49 UTC, MartyD1 approved these changes

2024-12-04 12:34 UTC, closed without merging